name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - monorepo
      - master
      - develop

jobs:
  lint:
    name: 'lint'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Make build
        run: yarn run build
      - name: Run eslint
        run: yarn run elint
  test:
    name: 'test'
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install plugin dependencies
        run: yarn install --frozen-lockfile
      - name: Build the packages
        run: yarn run build
      - name: Install playground dependencies
        run: yarn playground:install --frozen-lockfile --unsafe-perm
      - name: Run integration tests
        run: NODE_ENV=ci yarn test:integration


